### PR TITLE
Amy/questions controller

### PR DESCRIPTION
**Pull request by amyhliao**
@dj-m @walsh9 @RebeccaKleinberg 

Got stuck on getting the choices to appear in the 'show' view. I had:
 <% @question.choices.each do |choice| %>
        <input type="radio" name="choice[text]"> <%= choice.text %><br>
  <% end %>

but its only showing the choices for question_id: 1. Can you guys please take a look and see if theres any errors in my code? Thanks!

### CODE REVIEW

**Comment by dj-m** [comment]
Hey, @walsh9 @RebeccaKleinberg we may not need this show route for the question if we allow users to add questions in the survey show route. What do you think?

**Comment by walsh9** [comment]
I'm kind of confused in general as to how some of the routes on the trello board apply to the wireframes we made on the whiteboard.

For example, do we need routes for the individual choices? I don't think we have any pages dealing with things on a choice by choice level.

**Comment by walsh9** [comment]
I do already have answering questions in the show route for the survey, because we decided to show them all on one page.

**Comment by dj-m** [comment]
Go ahead and delete the ones that don't make sense, since a bunch of them were folded in together like you mentioned.

**Comment by dj-m** [comment]
Cool, so we don't need Amy's show route for questions, then? Let's edit that out :)

**Comment by walsh9** [comment]
actually right now i have `get '/surveys/:id'` showing the form to take a survey, maybe that route should it be showing the results instead.  When you take a survey you create a new response in the database, so the taking a survey form should probably be something like `get '/surveys/:id/responses/new'`. (i already have it posting to`/surveys/:id/responses` )

Either way I don't think we have a page for showing individual questions.

The way I see it the flow for creating a survey would go like this.

`get '/surveys/new'` - show the "title your survey form", posts to `/surveys`

`post '/surveys'` - create the survey in the database, redirect to `survey/:id/questions/new`
`get '/surveys/:id/questions/new'` (questions controller) - form for adding a question and its choices (shows existing questions at bottom), "add question" button posts to `surveys/:id/questions` "done" button      (separate form or just a link) just takes you to i don't know the results page maybe? (`get '/surveys/:id/'`)

`post '/surveys/:id/questions'` (questions controller) - adds a new question and its choices to the survey in the database, redirects back to `/survey/:id/questions/new` to add more questions

**Comment by dj-m** [comment]
The 'done' button on 'surveys/:id/questions' could probably just take you to '/surveys'... would results be better contained in the profile section?

**Comment by dj-m** [comment]
That flow makes a lot of sense. The trello routes were more goal posts to make sure we considered all the models/controllers and then edit the cards based on how things shaked out in the coding process...

**Comment by walsh9** [comment]
I feel like having the `surveys/show` view (`get '/surveys/:id'`) show all the details/results of a survey is okay.  We can restrict access to the link by user or however we want later. We can link to these from the profile or whereever.

Right now I have the survey taking there, but like I mentioned, the survey taking form is actually the `responses/new` view; it's the form to create a new response, so i'd like to move it to `get '/surveys/:id/responses/new'`

**Comment by dj-m** [comment]
@walsh9 right, that's a great idea to move forward with...

**Comment by walsh9** [comment]
Does anyone mind if I open an issue and try to map the rest of the routes to the wireframes.

**Comment by dj-m** [comment]
I'm good, go ahead.

**Comment by walsh9** [comment]
https://github.com/nyc-mud-turtles-2015/survey-orangutan/issues/6

**Pull request merged**
